language: cpp

compiler: gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install build-essential libgl1-mesa-dev sqlite3 libsqlite3-dev libqt4-dev qt4-qmake libqt4-sql-sqlite -y

install:
  - qmake
  - make
  
script:
  - make
